on: []

name: CodeGuard

env:
  CHATGPT_COOKIES: ${{ secrets.CHATGPT_COOKIES }}
  CHATGPT_AUTH_TOKEN: ${{ secrets.CHATGPT_TOKEN }} 
jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR.
    steps:
      - name: ChatGPT comment
        uses: mzbac/codeguard-gpt-action@0.0.5
        with:
          number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: CodeGuard

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: install packages
        run: npm i

    - name: chatgpt review PR
      run: npx tsx ./codeguard/main.ts
      with:
        number: ${{ github.event.pull_request.number }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_COOKIES: ${{ secrets.CHATGPT_COOKIES }}
          CHATGPT_AUTH_TOKEN: ${{ secrets.CHATGPT_TOKEN }} 