on: [pull_request]

name: CodeGuard
env:
  CHATGPT_COOKIES: ${{ secrets.CHATGPT_COOKIES }}
  CHATGPT_AUTH_TOKEN: ${{ secrets.CHATGPT_TOKEN }} 
jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR.
    steps:
      - name: ChatGPT comment
        uses: mzbac/codeguard-gpt-action@0.0.5
        with:
          number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
